- name: Install git
  apt:
    name: git
    state: present

- name: Clone a repo with separate git directory
  ansible.builtin.git:
    repo: "{{ cadavre_exquis_git_url }}"
    dest: "{{ cadavre_exquis_location }}"

- name: Install cadavre exquis chart
  ansible.builtin.shell:
    cmd: helm install cloud-cadavre-exquis ./helm/ --set dispatcher.replica=3 --set dispatcher.domain="cadavre.simonlucido.com" --set subject.replica=3 --set verb.replica=3 --set adjective.replica=3 
    chdir: "{{ cadavre_exquis_location }}"
